# Generated by Django 2.2 on 2019-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190426_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='login_count',
            new_name='login_counter',
        ),
    ]
